### ISSUE TITLE
Reason for Result?

### ISSUE THREAD

**Issue by tom95** [builttoroam/device_calendar#226]
Hi, great plugin!

I was wondering whether you could provide an insight on why the Result class exists? Naively, it appears that it will act in exactly the same way as a Future, providing a binary result of either success or failure, so either coming with the resolve data or the error that caused the rejection.

Should it indeed be equivalent, I would propose with this issue to have the API moved to just returning Futures everywhere in the next major version, which I believe would greatly simplify app code, especially in async methods and for error handling.

**Comment by nickrandolph** [comment]
@tom95 The Result class is designed to provide more context back to the caller. For example, rather than just throwing an exception, it returns false along with error messages. Agreed, this does perhaps add an additional layer of complexity but we wanted to make sure that we didn't expose any exceptions that might tear down the calling app. Happy to reconsider this if you wanted to propose a change in a PR. 
FYI I'm closing this issue but don't take this as a sign that you shouldn't contribute - feel free to PR any change you think we should adopt.
