### ISSUE TITLE
Open the device calendar app?

### ISSUE THREAD

**Issue by duzenko** [builttoroam/device_calendar#271]
I have to redirect the user to the calendar after creating the event in my code.
I would like the plugin to be able to open the device calendar app for that.

**Comment by andzejsw** [comment]
When creating event, you can listen if it is added. In the example app is following code: 
```
var createEventResult = await _deviceCalendarPlugin.createOrUpdateEvent(_event);
if (createEventResult?.isSuccess == true) {
  // Code for opening device calendar here
}
```
Fast search for me lead to this stackoverflow post: https://stackoverflow.com/questions/54971724/we-need-to-launch-mobile-devices-calendar-from-flutter-app-icon-ontap
Top answer suggest, that you can open native device calendar on phone like this: **_"If you have url_launcher integrated then calshow:// for iOS and content://com.android.calendar/time/ for Android should work."_**
Since this now can be done easelly, I see no reason to implement this logic also in device calendar plugin.

**Comment by duzenko** [comment]
Sorry, I disagree
If I wanted to write native code, I would not have bothered with Flutter at all

**Comment by andzejsw** [comment]
@duzenko In my explanation how to do that there is no native code used. Only flutter code and integration with flutter package.

**Comment by nickrandolph** [comment]
@duzenko I agree with @andzejsw this library isn't about launching or interacting with any of the built in experiences (eg device calendar app). There are, or should be, alternative packages for that. 
This package is solely focused on interacting with the calendar APIs exposed by the individual platforms.
