### ISSUE TITLE
Retrieving events returns incorrect start and end time

### ISSUE THREAD

**Issue by nitinjavakid** [builttoroam/device_calendar#374]
Json decode code from plugin to dart code is not using the correct keys. This results in incorrect start and end time of events.

**Comment by thomassth** [comment]
Oh boy

I traced this back to #316. Apparently said dart file changed, but not the corresponding swift and kotlin files.

In any case it seems to only affect retrieval and not saving events. (Otherwise I would found out on my project)

I'll be pushing fixes in the next few hours.

We really need to invest more effort writing tests to prevent these trivial things.

**Comment by nitinjavakid** [comment]
I can confirm that this has been fixed in 4.0.1. Thanks.
