### ISSUE TITLE
libs incompatible

### ISSUE THREAD

**Issue by zhuyangyang-lingoace** [builttoroam/device_calendar#397]
use the device calendar 4.0.1
meta: ^1.7.0
but our  flutter sdk is 2.2.3
meta 1.3.0

**Comment by thomassth** [comment]
What plugin is stopping you from updating?

Maybe ask them to update too?

**Comment by zhuyangyang-lingoace** [comment]
flutter_localizations and flutter_test
It is from flutter sdk.
So I upgrade our flutter if I use this lib ?.

**Comment by thomassth** [comment]
Have you tried?

**Comment by andzejsw** [comment]
> flutter_localizations and flutter_test It is from flutter sdk. So I upgrade our flutter if I use this lib ?

As far as I see, you have 2 options. Updating flutter version to latest stable (which is most logical, cause code always needs to be updated to stable and secure versions) or use older "Device calendar" version, which is compatible with flutter 2.2.3.

**Comment by zhuyangyang-lingoace** [comment]
@andzejsw Yes, currently, I  use the Device Calendar 3.9.0. That's ok. But I just want to use the latest lib. But upgrade the flutter sdk is a  little heavy task. We can't upgrade the Flutter because of this lib. Maybe you don't have the plan to adapt the previous version. Actually, I found the latest version also upgrade the kotlin.  haha, Maybe you don't have the project's burden

**Comment by thomassth** [comment]
We have repeatedly asked what prevented you from adopting the latest flutter versions. You have given us nothing to work with.

We all have our own projects utilizing this plugin, and we saw no such problem raised yet. If enough people needed support on lower flutter versions, we may consider it. But latest stable versions come first. 

Feel free to raise your need to update to the relevant developers. Or find out what caused your problem and submit a PR if suitable, so that we can review.
