### ISSUE TITLE
Not working in the built and release mode

### ISSUE THREAD

**Issue by ARAVINDKARATE** [builttoroam/device_calendar#464]
I have integrated the device calendar plugin in my project and all the functions are working fine when I run the code but when I run it in release mode or make a built to release, these functionalities are not working

**Comment by SuperKrallan** [comment]
I am not having this problem. I think you need to be more specific what is not working for you in order to get better help.

**Comment by zakton5** [comment]
Can confirm that adding events to a calendar does not work in release mode. I have used thoroughly tested this in debug mode and it works fine. In release mode, I am attempting to catch the error which fails the following `is` check. It is clearly a `ResultError` but somehow `ex is ResultError returns false. In summary, I have no way to figure out what the problem is.

```
try {
   await _calendarPlugin.createOrUpdateEvent(deviceEvent)
} catch (ex) {
  if (ex is ResultError) {
    print('result error');
  }
}
```

**Comment by zakton5** [comment]
Apparently this library throws a `List<ResultError>` instead of a single `ResultError`. Here is my code:

```
final calendarsResult = await _calendarPlugin.retrieveCalendars();
if (!calendarsResult.isSuccess) {
  throw 'Failed to retrieve calendars';
} else if (calendarsResult.data == null || calendarsResult.data!.isEmpty) {
  throw 'Could not find any calendars';
}

calendarsResult.data!.forEach((calendar) {
  print('${calendar.id} ${calendar.name}, default: ${calendar.isDefault}, readOnly: ${calendar.isReadOnly}');
});
```

In debug mode in successfully retrieves all calendars and print the data correctly. In release mode, `calendar.id`, `calendar.name`, etc. are all `null`. So the core problem is that I don't actually have a calendarId to save events to because it is null.

**Comment by thomassth** [comment]
@ARAVINDKARATE @zakton5  Please provide more details, such as: 
- manufacturer of the phones (I think Samsung's local calendar was once problematic)
- were said calendar local only, or were they synced with a specific cloud service provider (Google / Microsoft / Apple / Proton etc)
- Version of your phone and the plugin, maybe run a `flutter doctor -v` while you're at it
- were calendar permissions granted to the app at the time

**Comment by zakton5** [comment]
I found the section on the R8 proguard issue. I followed those steps and everything works well now.
